- job:
    name: neutron-tempest-plugin
    parent: devstack-tempest
    abstract: true
    description: |
      Perform setup common to all Neutron tempest tests
    roles:
      - zuul: openstack-dev/devstack
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-tempest-plugin
      - openstack/tempest
    vars:
      tempest_concurrency: 4
      tox_envlist: all
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/neutron-tempest-plugin
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-domain-ports,dns-integration,dvr,empty-string-filtering,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,qos-fip,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,port-mac-address-regenerate,port-security-groups-filtering,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-segment,standard-attr-timestamp,standard-attr-tag,subnet_allocation,trunk,trunk-details
      devstack_plugins:
        neutron: git://git.openstack.org/openstack/neutron.git
        neutron-tempest-plugin: git://git.openstack.org/openstack/neutron-tempest-plugin.git
      devstack_services:
        tls-proxy: false
        tempest: true
        neutron-dns: true
        neutron-qos: true
        neutron-segments: true
        neutron-trunk: true
      devstack_local_conf:
        post-config:
          $NEUTRON_CONF:
            QUOTAS:
              quota_router: 100
              quota_floatingip: 500
              quota_security_group: 100
              quota_security_group_rule: 1000
          # NOTE(slaweq): We can get rid of this hardcoded absolute path when
          # devstack-tempest job will be switched to use lib/neutron instead of
          # lib/neutron-legacy
          /$NEUTRON_CORE_PLUGIN_CONF:
            ml2:
              type_drivers: flat,geneve,vlan,gre,local,vxlan
            ml2_type_vlan:
              network_vlan_ranges: foo:1:10
            ml2_type_vxlan:
              vni_ranges: 1:2000
            ml2_type_gre:
              tunnel_id_ranges: 1:1000
          $NEUTRON_L3_CONF:
            agent:
              availability_zone: nova
          $NEUTRON_DHCP_CONF:
            agent:
              availability_zone: nova
          /etc/neutron/api-paste.ini:
            composite:neutronapi_v2_0:
              use: call:neutron.auth:pipeline_factory
              noauth: cors request_id catch_errors osprofiler extensions neutronapiapp_v2_0
              keystone: cors request_id catch_errors osprofiler authtoken keystonecontext extensions neutronapiapp_v2_0
        test-config:
          $TEMPEST_CONFIG:
            neutron_plugin_options:
              provider_vlans: foo,
              agent_availability_zone: nova
              image_is_advanced: true
              available_type_drivers: flat,geneve,vlan,gre,local,vxlan
    irrelevant-files: &tempest-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^releasenotes/.*$
      - ^doc/.*$
      - ^setup.cfg$
      - ^.*\.rst$
      - ^neutron/locale/.*$
      - ^neutron/tests/unit/.*$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: neutron-tempest-plugin-api
    parent: neutron-tempest-plugin
    vars:
      tempest_test_regex: ^neutron_tempest_plugin\.api
      devstack_services:
        neutron-log: true
      devstack_local_conf:
        post-config:
          # NOTE(slaweq): We can get rid of this hardcoded absolute path when
          # devstack-tempest job will be switched to use lib/neutron instead of
          # lib/neutron-legacy
          /$NEUTRON_CORE_PLUGIN_CONF:
            AGENT:
              tunnel_types: gre,vxlan
            network_log:
              local_output_log_base: /tmp/test_log.log

- job:
    name: neutron-tempest-plugin-api-queens
    parent: neutron-tempest-plugin-api
    override-checkout: stable/queens
    vars:
      branch_override: stable/queens
      devstack_localrc:
        # TODO(slaweq): find a way to put this list of extensions in
        # neutron repository and keep it different per branch,
        # then it could be removed from here
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-domain-ports,dns-integration,dvr,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-timestamp,standard-attr-tag,subnet_allocation,tag,tag-ext,trunk,trunk-details

- job:
    name: neutron-tempest-plugin-api-rocky
    parent: neutron-tempest-plugin-api
    override-checkout: stable/rocky
    vars:
      branch_override: stable/rocky
      devstack_localrc:
        # TODO(slaweq): find a way to put this list of extensions in
        # neutron repository and keep it different per branch,
        # then it could be removed from here
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-domain-ports,dns-integration,dvr,empty-string-filtering,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,qos-fip,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,port-mac-address-regenerate,port-security-groups-filtering,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-segment,standard-attr-timestamp,standard-attr-tag,subnet_allocation,trunk,trunk-details

- job:
    name: neutron-tempest-plugin-scenario
    parent: neutron-tempest-plugin
    abstract: true
    description: |
      Perform setup common to all tempest scenario test jobs.
    vars:
      tempest_test_regex: ^neutron_tempest_plugin\.scenario
      devstack_localrc:
        PHYSICAL_NETWORK: default
        DOWNLOAD_DEFAULT_IMAGES: false
        IMAGE_URLS: http://cloud-images.ubuntu.com/releases/16.04/release-20180622/ubuntu-16.04-server-cloudimg-amd64-disk1.img,
        DEFAULT_INSTANCE_TYPE: ds512M
        DEFAULT_INSTANCE_USER: ubuntu
        BUILD_TIMEOUT: 784
        LIBVIRT_TYPE: kvm
      devstack_services:
        cinder: true

- job:
    name: neutron-tempest-plugin-scenario-linuxbridge
    parent: neutron-tempest-plugin-scenario
    timeout: 10000
    vars:
      devstack_localrc:
        Q_AGENT: linuxbridge
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-domain-ports,dns-integration,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,qos-fip,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,port-security-groups-filtering,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-timestamp,standard-attr-tag,subnet_allocation,tag,tag-ext,trunk,trunk-details
      devstack_local_conf:
        post-config:
          $NEUTRON_CONF:
            DEFAULT:
              enable_dvr: false
            AGENT:
              debug_iptables_rules: true
          # NOTE(slaweq): We can get rid of this hardcoded absolute path when
          # devstack-tempest job will be switched to use lib/neutron instead of
          # lib/neutron-legacy
          /$NEUTRON_CORE_PLUGIN_CONF:
            ml2:
              type_drivers: flat,vlan,local,vxlan
        test-config:
          $TEMPEST_CONFIG:
            neutron_plugin_options:
              available_type_drivers: flat,vlan,local,vxlan

- job:
    name: neutron-tempest-plugin-scenario-linuxbridge-queens
    parent: neutron-tempest-plugin-scenario-linuxbridge
    override-checkout: stable/queens
    vars:
      branch_override: stable/queens
      devstack_localrc:
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-integration,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,qos-fip,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,port-security-groups-filtering,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-timestamp,standard-attr-tag,subnet_allocation,tag,tag-ext,trunk,trunk-details

- job:
    name: neutron-tempest-plugin-scenario-linuxbridge-rocky
    parent: neutron-tempest-plugin-scenario-linuxbridge
    override-checkout: stable/rocky
    vars:
      branch_override: stable/rocky
      devstack_localrc:
        NETWORK_API_EXTENSIONS: address-scope,agent,allowed-address-pairs,auto-allocated-topology,availability_zone,binding,default-subnetpools,dhcp_agent_scheduler,dns-domain-ports,dns-integration,ext-gw-mode,external-net,extra_dhcp_opt,extraroute,fip-port-details,flavors,ip-substring-filtering,l3-flavors,l3-ha,l3_agent_scheduler,logging,metering,multi-provider,net-mtu,net-mtu-writable,network-ip-availability,network_availability_zone,pagination,port-security,project-id,provider,qos,qos-fip,quotas,quota_details,rbac-policies,router,router_availability_zone,security-group,port-security-groups-filtering,segment,service-type,sorting,standard-attr-description,standard-attr-revisions,standard-attr-timestamp,standard-attr-tag,subnet_allocation,tag,tag-ext,trunk,trunk-details

- job:
    name: neutron-tempest-plugin-dvr-multinode-scenario
    parent: legacy-dsvm-base-multinode
    run: playbooks/neutron-tempest-plugin-dvr-multinode-scenario/run.yaml
    post-run: playbooks/neutron-tempest-plugin-dvr-multinode-scenario/post.yaml
    nodeset: legacy-ubuntu-xenial-2-node
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/neutron
      - openstack/neutron-tempest-plugin
      - openstack/tempest
    irrelevant-files: *tempest-irrelevant-files
    voting: false

- job:
    name: neutron-tempest-plugin-dvr-multinode-scenario-queens
    parent: neutron-tempest-plugin-dvr-multinode-scenario
    override-checkout: stable/queens
    vars:
      branch_override: stable/queens

- job:
    name: neutron-tempest-plugin-dvr-multinode-scenario-rocky
    parent: neutron-tempest-plugin-dvr-multinode-scenario
    override-checkout: stable/rocky
    vars:
      branch_override: stable/rocky

- job:
    name: neutron-tempest-plugin-designate-scenario
    parent: neutron-tempest-plugin-scenario
    description: Neutron designate integration scenario
    required-projects:
      - openstack/designate
      - openstack/designate-dashboard
      - openstack/designate-tempest-plugin
    timeout: 3600
    vars:
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/designate-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        DESIGNATE_BACKEND_DRIVER: bind9
      devstack_plugins:
        designate: git://git.openstack.org/openstack/designate.git
      devstack_services:
        cinder: false
        designate: true
      tempest_test_regex: ^neutron_tempest_plugin\.scenario\.test_dns_integration
    irrelevant-files: *tempest-irrelevant-files

- job:
    name: neutron-tempest-plugin-designate-scenario-queens
    parent: neutron-tempest-plugin-designate-scenario
    override-checkout: stable/queens
    vars:
      branch_override: stable/queens

- job:
    name: neutron-tempest-plugin-designate-scenario-rocky
    parent: neutron-tempest-plugin-designate-scenario
    override-checkout: stable/rocky
    vars:
      branch_override: stable/rocky

- project-template:
    name: neutron-tempest-plugin-jobs
    check:
      jobs:
        - neutron-tempest-plugin-api
        - neutron-tempest-plugin-designate-scenario
        - neutron-tempest-plugin-dvr-multinode-scenario
        - neutron-tempest-plugin-scenario-linuxbridge
        - build-openstack-sphinx-docs
    gate:
      jobs:
        - neutron-tempest-plugin-api
        - neutron-tempest-plugin-scenario-linuxbridge
        - build-openstack-sphinx-docs

- project-template:
    name: neutron-tempest-plugin-jobs-queens
    check:
      jobs:
        - neutron-tempest-plugin-api-queens
        - neutron-tempest-plugin-designate-scenario-queens
        - neutron-tempest-plugin-dvr-multinode-scenario-queens
        - neutron-tempest-plugin-scenario-linuxbridge-queens
    gate:
      jobs:
        - neutron-tempest-plugin-api-queens

- project-template:
    name: neutron-tempest-plugin-jobs-rocky
    check:
      jobs:
        - neutron-tempest-plugin-api-rocky
        - neutron-tempest-plugin-designate-scenario-rocky
        - neutron-tempest-plugin-dvr-multinode-scenario-rocky
        - neutron-tempest-plugin-scenario-linuxbridge-rocky
    gate:
      jobs:
        - neutron-tempest-plugin-api-rocky

- project:
    templates:
      - neutron-tempest-plugin-jobs
      - neutron-tempest-plugin-jobs-queens
      - neutron-tempest-plugin-jobs-rocky
      - check-requirements
      - tempest-plugin-jobs
