- project-template:
    name: neutron-tempest-plugin-jobs
    check:
      jobs:
        - neutron-tempest-plugin-api
        - neutron-tempest-plugin-scenario-linuxbridge
        - neutron-tempest-plugin-scenario-openvswitch
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid
        - neutron-tempest-plugin-scenario-ovn
        - neutron-tempest-plugin-designate-scenario
    gate:
      jobs:
        - neutron-tempest-plugin-api
        - neutron-tempest-plugin-scenario-linuxbridge
        - neutron-tempest-plugin-scenario-openvswitch
        - neutron-tempest-plugin-scenario-ovn
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario
        - neutron-tempest-plugin-scenario-openvswitch-distributed-dhcp
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-distributed-dhcp


- project-template:
    name: neutron-tempest-plugin-jobs-queens
    check:
      jobs:
        - neutron-tempest-plugin-api-queens
        - neutron-tempest-plugin-scenario-linuxbridge-queens
        - neutron-tempest-plugin-scenario-openvswitch-queens
    gate:
      jobs:
        - neutron-tempest-plugin-api-queens
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-queens


- project-template:
    name: neutron-tempest-plugin-jobs-rocky
    check:
      jobs:
        - neutron-tempest-plugin-api-rocky
        - neutron-tempest-plugin-scenario-linuxbridge-rocky
        - neutron-tempest-plugin-scenario-openvswitch-rocky
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-rocky
        - neutron-tempest-plugin-designate-scenario-rocky
    gate:
      jobs:
        - neutron-tempest-plugin-api-rocky
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-rocky


- project-template:
    name: neutron-tempest-plugin-jobs-stein
    check:
      jobs:
        - neutron-tempest-plugin-api-stein
        - neutron-tempest-plugin-scenario-linuxbridge-stein
        - neutron-tempest-plugin-scenario-openvswitch-stein
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-stein
        - neutron-tempest-plugin-designate-scenario-stein
    gate:
      jobs:
        - neutron-tempest-plugin-api-stein
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-stein


- project-template:
    name: neutron-tempest-plugin-jobs-train
    check:
      jobs:
        - neutron-tempest-plugin-api-train
        - neutron-tempest-plugin-scenario-linuxbridge-train
        - neutron-tempest-plugin-scenario-openvswitch-train
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-train
        - neutron-tempest-plugin-designate-scenario-train
    gate:
      jobs:
        - neutron-tempest-plugin-api-train
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-train


- project-template:
    name: neutron-tempest-plugin-jobs-ussuri
    check:
      jobs:
        - neutron-tempest-plugin-api-ussuri
        - neutron-tempest-plugin-scenario-linuxbridge-ussuri
        - neutron-tempest-plugin-scenario-openvswitch-ussuri
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-ussuri
        - neutron-tempest-plugin-scenario-ovn-ussuri
        - neutron-tempest-plugin-designate-scenario-ussuri
    gate:
      jobs:
        - neutron-tempest-plugin-api-ussuri
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-ussuri


- project-template:
    name: neutron-tempest-plugin-jobs-victoria
    check:
      jobs:
        - neutron-tempest-plugin-api-victoria
        - neutron-tempest-plugin-scenario-linuxbridge-victoria
        - neutron-tempest-plugin-scenario-openvswitch-victoria
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-victoria
        - neutron-tempest-plugin-scenario-ovn-victoria
        - neutron-tempest-plugin-designate-scenario-victoria
    gate:
      jobs:
        - neutron-tempest-plugin-api-victoria
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-victoria


- project-template:
    name: neutron-tempest-plugin-jobs-wallaby
    check:
      jobs:
        - neutron-tempest-plugin-api-wallaby
        - neutron-tempest-plugin-scenario-linuxbridge-wallaby
        - neutron-tempest-plugin-scenario-openvswitch-wallaby
        - neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-wallaby
        - neutron-tempest-plugin-scenario-ovn-wallaby
        - neutron-tempest-plugin-designate-scenario-wallaby
    gate:
      jobs:
        - neutron-tempest-plugin-api-wallaby
    #TODO(slaweq): Move neutron-tempest-plugin-dvr-multinode-scenario out of
    #              the experimental queue when it will be more stable
    experimental:
      jobs:
        - neutron-tempest-plugin-dvr-multinode-scenario-wallaby


- project:
    templates:
      - build-openstack-docs-pti
      - neutron-tempest-plugin-jobs
      - neutron-tempest-plugin-jobs-ussuri
      - neutron-tempest-plugin-jobs-victoria
      - neutron-tempest-plugin-jobs-wallaby
      - check-requirements
      - tempest-plugin-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-tempest-plugin-sfc
        - neutron-tempest-plugin-sfc-ussuri
        - neutron-tempest-plugin-sfc-victoria
        - neutron-tempest-plugin-sfc-wallaby
        - neutron-tempest-plugin-bgpvpn-bagpipe
        - neutron-tempest-plugin-bgpvpn-bagpipe-ussuri
        - neutron-tempest-plugin-bgpvpn-bagpipe-victoria
        - neutron-tempest-plugin-bgpvpn-bagpipe-wallaby
        - neutron-tempest-plugin-dynamic-routing
        - neutron-tempest-plugin-dynamic-routing-ussuri
        - neutron-tempest-plugin-dynamic-routing-victoria
        - neutron-tempest-plugin-dynamic-routing-wallaby
        - neutron-tempest-plugin-vpnaas
        - neutron-tempest-plugin-vpnaas-ussuri
        - neutron-tempest-plugin-vpnaas-victoria
        - neutron-tempest-plugin-vpnaas-wallaby
        - neutron-tempest-plugin-tap-as-a-service

    gate:
      jobs:
        - neutron-tempest-plugin-sfc
        - neutron-tempest-plugin-bgpvpn-bagpipe
        - neutron-tempest-plugin-dynamic-routing

    experimental:
      jobs:
        - neutron-tempest-plugin-fwaas-ussuri:
            # TODO(slaweq): switch it to be voting when bug
            # https://bugs.launchpad.net/neutron/+bug/1858645 will be fixed
            voting: false
