- job:
    name: neutron-tempest-plugin-api-train
    parent: neutron-tempest-plugin-api
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: &required-projects-train
      - openstack/neutron
      - name: openstack/neutron-tempest-plugin
        override-checkout: 1.5.0
      - openstack/tempest
    vars:
      devstack_services:
        # Disable OVN services
        br-ex-tcpdump: false
        br-int-flows: false
        ovn-controller: false
        ovn-northd: false
        ovs-vswitchd: false
        ovsdb-server: false
        q-ovn-metadata-agent: false
        # Neutron services
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        q-metering: true
      branch_override: stable/train
      # TODO(slaweq): find a way to put this list of extensions in
      # neutron repository and keep it different per branch,
      # then it could be removed from here
      network_api_extensions_common: &api_extensions
        - address-scope
        - agent
        - allowed-address-pairs
        - auto-allocated-topology
        - availability_zone
        - binding
        - default-subnetpools
        - dhcp_agent_scheduler
        - dns-domain-ports
        - dns-integration
        - empty-string-filtering
        - expose-port-forwarding-in-fip
        - expose-l3-conntrack-helper
        - ext-gw-mode
        - external-net
        - extra_dhcp_opt
        - extraroute
        - extraroute-atomic
        - filter-validation
        - fip-port-details
        - flavors
        - floating-ip-port-forwarding
        - floatingip-pools
        - ip-substring-filtering
        - l3-conntrack-helper
        - l3-flavors
        - l3-ha
        - l3_agent_scheduler
        - logging
        - metering
        - multi-provider
        - net-mtu
        - net-mtu-writable
        - network-ip-availability
        - network_availability_zone
        - network-segment-range
        - pagination
        - port-resource-request
        - port-mac-address-regenerate
        - port-security
        - port-security-groups-filtering
        - project-id
        - provider
        - qos
        - qos-bw-minimum-ingress
        - qos-fip
        - quotas
        - quota_details
        - rbac-policies
        - rbac-security-groups
        - router
        - router-admin-state-down-before-update
        - router_availability_zone
        - security-group
        - segment
        - service-type
        - sorting
        - standard-attr-description
        - standard-attr-revisions
        - standard-attr-segment
        - standard-attr-tag
        - standard-attr-timestamp
        - subnet_allocation
        - subnet-service-types
        - subnetpool-prefix-ops
        - trunk
        - trunk-details
        - uplink-status-propagation
      network_api_extensions_tempest:
        - dvr
      network_available_features: &available_features
        -
      devstack_localrc:
        NEUTRON_DEPLOY_MOD_WSGI: false
        NETWORK_API_EXTENSIONS: "{{ (network_api_extensions_common + network_api_extensions_tempest) | join(',') }}"
        Q_AGENT: openvswitch
        Q_ML2_TENANT_NETWORK_TYPE: vxlan
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: openvswitch
        ML2_L3_PLUGIN: router
      devstack_local_conf:
        post-config:
          # NOTE(slaweq): We can get rid of this hardcoded absolute path when
          # devstack-tempest job will be switched to use lib/neutron instead of
          # lib/neutron-legacy
          /$NEUTRON_CORE_PLUGIN_CONF:
            AGENT:
              tunnel_types: gre,vxlan
            ml2:
              type_drivers: flat,geneve,vlan,gre,local,vxlan
        test-config:
          $TEMPEST_CONFIG:
            neutron_plugin_options:
              available_type_drivers: flat,geneve,vlan,gre,local,vxlan

- job:
    name: neutron-tempest-plugin-scenario-openvswitch-train
    parent: neutron-tempest-plugin-scenario-openvswitch
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions: *api_extensions
      network_available_features: *available_features
      devstack_localrc:
        NETWORK_API_EXTENSIONS: "{{ network_api_extensions | join(',') }}"
        ADVANCED_INSTANCE_TYPE: ds512M
      devstack_local_conf:
        post-config:
          $NEUTRON_L3_CONF:
            DEFAULT:
              # NOTE(slaweq): on Bionic keepalived doesn't knows this option yet
              keepalived_use_no_track: False
        test-config:
          $TEMPEST_CONFIG:
            network-feature-enabled:
              available_features: ""
            neutron_plugin_options:
              ipv6_metadata: False

- job:
    name: neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid-train
    parent: neutron-tempest-plugin-scenario-openvswitch-iptables_hybrid
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions: *api_extensions
      network_available_features: *available_features
      devstack_localrc:
        NETWORK_API_EXTENSIONS: "{{ network_api_extensions | join(',') }}"
        ADVANCED_INSTANCE_TYPE: ds512M
      devstack_local_conf:
        post-config:
          $NEUTRON_L3_CONF:
            DEFAULT:
              # NOTE(slaweq): on Bionic keepalived don't knows this option yet
              keepalived_use_no_track: False
        test-config:
          $TEMPEST_CONFIG:
            network-feature-enabled:
              available_features: ""
            neutron_plugin_options:
              ipv6_metadata: False

- job:
    name: neutron-tempest-plugin-scenario-linuxbridge-train
    parent: neutron-tempest-plugin-scenario-linuxbridge
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions: *api_extensions
      network_available_features: *available_features
      devstack_localrc:
        NETWORK_API_EXTENSIONS: "{{ network_api_extensions | join(',') }}"
        ADVANCED_INSTANCE_TYPE: ds512M
      devstack_local_conf:
        post-config:
          $NEUTRON_L3_CONF:
            DEFAULT:
              # NOTE(slaweq): on Bionic keepalived don't knows this option yet
              keepalived_use_no_track: False
        test-config:
          $TEMPEST_CONFIG:
            network-feature-enabled:
              available_features: ""
            neutron_plugin_options:
              ipv6_metadata: False

- job:
    name: neutron-tempest-plugin-dvr-multinode-scenario-train
    parent: neutron-tempest-plugin-dvr-multinode-scenario
    nodeset: openstack-two-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      network_api_extensions_common: *api_extensions
      branch_override: stable/train

- job:
    name: neutron-tempest-plugin-designate-scenario-train
    parent: neutron-tempest-plugin-designate-scenario
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions_common: *api_extensions
      devstack_localrc:
        ADVANCED_INSTANCE_TYPE: ds512M

- job:
    name: neutron-tempest-plugin-sfc-train
    parent: neutron-tempest-plugin-sfc
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions_common: *api_extensions

- job:
    name: neutron-tempest-plugin-bgpvpn-bagpipe-train
    parent: neutron-tempest-plugin-bgpvpn-bagpipe
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions: *api_extensions

- job:
    name: neutron-tempest-plugin-fwaas-train
    parent: neutron-tempest-plugin-fwaas-ussuri
    nodeset: openstack-single-node-bionic
    override-checkout: stable/train
    required-projects: *required-projects-train
    vars:
      branch_override: stable/train
      network_api_extensions_common: *api_extensions
